package main

import (
	"context"
	"embed"
	_ "embed"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/assetserver"
	"github.com/wailsapp/wails/v2/pkg/options/windows"
	wailsruntime "github.com/wailsapp/wails/v2/pkg/runtime"

	"GameSaver/internal/config"
	"GameSaver/internal/logging"
	"GameSaver/internal/tray"
)

//go:embed all:frontend/dist
var assets embed.FS

// trayIcon is a multi-resolution Windows ICO used by getlantern/systray.
// Generated by `go run ./cmd/gen-icon` alongside build/appicon.png and
// committed so CI builds embed the right bytes.
//
//go:embed internal/tray/icon.ico
var trayIcon []byte

func main() {
	cfg, err := config.Load()
	if err != nil {
		slog.Error("load config", "err", err)
		os.Exit(1)
	}
	if err := logging.Setup(cfg); err != nil {
		slog.Error("setup logging", "err", err)
		os.Exit(1)
	}
	slog.Info("GameSaver starting", "version", AppVersion, "userData", cfg.UserDataDir)

	app := NewApp(cfg)

	// Start tray on a background goroutine. On Windows the systray loop is
	// happy off the main thread (macOS would require otherwise; we're Windows
	// only). Tray "Open" / "Backup all" / "Watcher" / "Quit" all proxy back
	// to App via the AppController interface.
	tray.Init(trayIcon, app)
	go tray.Run()

	err = wails.Run(&options.App{
		Title:            "GameSaver",
		Width:            1280,
		Height:           820,
		MinWidth:         900,
		MinHeight:        600,
		BackgroundColour: &options.RGBA{R: 17, G: 17, B: 23, A: 1},
		AssetServer: &assetserver.Options{
			Assets:  assets,
			Handler: coversHandler(cfg),
		},
		OnStartup:  func(ctx context.Context) { app.Startup(ctx) },
		OnShutdown: func(ctx context.Context) { app.Shutdown(ctx) },
		// Close button hides the window instead of killing the process —
		// app keeps running in the tray (watcher etc. stay alive). We hook
		// OnBeforeClose and call WindowHide ourselves rather than relying on
		// HideWindowOnClose, because the latter routes through the full close
		// path internally (visible as a 1–2 s freeze in WebView2 before the
		// hide kicks in). Returning true cancels the actual close.
		OnBeforeClose: func(ctx context.Context) bool {
			wailsruntime.WindowHide(ctx)
			return true
		},
		// Only one instance allowed — a second exec (e.g. user double-clicks
		// the tray-resident exe again) hands off to the running instance and
		// exits, otherwise we get duplicate playtime sessions, duplicate
		// watchers, duplicate trays, etc. The callback unhides + raises the
		// existing window so the user sees it pop up.
		SingleInstanceLock: &options.SingleInstanceLock{
			UniqueId: "GameSaver-LastSkywalkerER-single-instance",
			OnSecondInstanceLaunch: func(_ options.SecondInstanceData) {
				ctx := app.Context()
				if ctx == nil {
					return
				}
				wailsruntime.WindowShow(ctx)
				wailsruntime.WindowUnminimise(ctx)
				// Toggle always-on-top to force the OS to bring it forward
				// past the taskbar flash.
				wailsruntime.WindowSetAlwaysOnTop(ctx, true)
				wailsruntime.WindowSetAlwaysOnTop(ctx, false)
			},
		},
		Bind: []interface{}{app},
		Windows: &windows.Options{
			WebviewIsTransparent:              false,
			WindowIsTranslucent:               false,
			DisableFramelessWindowDecorations: false,
		},
	})
	tray.Quit()
	if err != nil {
		slog.Error("wails run", "err", err)
		os.Exit(1)
	}
}

// coversHandler returns an http.Handler that serves cached cover images.
// Requests to /covers/<filename> resolve to files under cfg.CoversDir().
// Anything else returns 404 so the embedded SPA index can take over.
func coversHandler(cfg *config.Config) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.URL.Path, "/covers/") {
			http.NotFound(w, r)
			return
		}
		name := strings.TrimPrefix(r.URL.Path, "/covers/")
		if name == "" || strings.Contains(name, "..") || strings.ContainsAny(name, `\/`) {
			http.NotFound(w, r)
			return
		}
		full := filepath.Join(cfg.CoversDir(), name)
		http.ServeFile(w, r, full)
	})
}

// AppVersion is overridden at build time via:
//
//	wails build -ldflags "-X main.AppVersion=v0.2.0"
//
// Local dev builds keep "dev" so the auto-updater skips the version check.
var AppVersion = "dev"
