// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {updater} from '../models';
import {bluetooth} from '../models';
import {context} from '../models';
import {match} from '../models';
import {main} from '../models';
import {config} from '../models';
import {stores} from '../models';
import {sunshine} from '../models';
import {audio} from '../models';
import {display} from '../models';
import {backup} from '../models';
import {pipeline} from '../models';

export function AddManualSaveLocation(arg1:string,arg2:string):Promise<domain.SaveLocation>;

export function AddSteamAccountViaLogin():Promise<domain.StoreAccount>;

export function AddStoreAccount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<domain.StoreAccount>;

export function AppVersion():Promise<string>;

export function ApplyUpdate():Promise<void>;

export function BackupAll():Promise<number>;

export function BackupGame(arg1:string):Promise<Array<domain.Snapshot>>;

export function CancelMonitorPick():Promise<void>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function ClearManifestOverride(arg1:string):Promise<void>;

export function ConnectBluetoothDevice(arg1:string):Promise<bluetooth.ConnectResult>;

export function Context():Promise<context.Context>;

export function DeepScanGame(arg1:string):Promise<Array<match.DeepScanResult>>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function DisableShellMode():Promise<void>;

export function DisconnectBluetoothDevice(arg1:string):Promise<void>;

export function EnableShellMode():Promise<void>;

export function FinishMonitorPick(arg1:string):Promise<void>;

export function GetAggregatedLibrary():Promise<Array<domain.LibraryCard>>;

export function GetAutoLoginStatus():Promise<main.AutoLoginStatus>;

export function GetCachedUpdate():Promise<updater.UpdateInfo>;

export function GetConfig():Promise<config.Config>;

export function GetGame(arg1:string):Promise<domain.GameView>;

export function GetShellModeStatus():Promise<main.ShellModeStatus>;

export function GetStoreClients():Promise<Array<stores.ClientStatus>>;

export function GetStoreLoginInfo(arg1:string):Promise<stores.LoginInfo>;

export function GetSunshineStatus():Promise<sunshine.Status>;

export function GetVolume():Promise<audio.VolumeInfo>;

export function HideGame(arg1:string,arg2:boolean):Promise<void>;

export function IsControllerConnected():Promise<boolean>;

export function IsWatcherEnabled():Promise<boolean>;

export function LaunchGame(arg1:string,arg2:string):Promise<void>;

export function ListAudioDevices():Promise<Array<audio.Device>>;

export function ListBluetoothDevices():Promise<Array<bluetooth.Device>>;

export function ListGames():Promise<Array<domain.GameView>>;

export function ListMonitors():Promise<Array<display.Monitor>>;

export function ListPlaySessions(arg1:string,arg2:number):Promise<Array<domain.PlaySession>>;

export function ListStoreAccounts():Promise<Array<domain.StoreAccount>>;

export function LockWorkstation():Promise<void>;

export function MakeSoleMonitor(arg1:string):Promise<void>;

export function MigrateSave(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MinimizeSelf():Promise<void>;

export function OpenAutoLoginConfigurator():Promise<void>;

export function OpenBackupFolder():Promise<void>;

export function OpenStoreClient(arg1:string):Promise<void>;

export function OpenStoreLoginPage(arg1:string):Promise<void>;

export function OpenSysinternalsAutologon():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function OpenWindowsBluetoothSettings():Promise<void>;

export function OpenWindowsSoundSettings():Promise<void>;

export function PairBluetoothDevice(arg1:string):Promise<void>;

export function PickFolder(arg1:string):Promise<string>;

export function PrepareMonitorPick():Promise<main.MonitorPickPrep>;

export function QuitApp():Promise<void>;

export function RebootWorkstation():Promise<void>;

export function ReconcileBackups():Promise<backup.ReconcileResult>;

export function RematchGame(arg1:string,arg2:string):Promise<void>;

export function RemoveSaveLocation(arg1:string):Promise<void>;

export function RemoveStoreAccount(arg1:string):Promise<void>;

export function RestartApp():Promise<void>;

export function RestoreMonitorConfig():Promise<void>;

export function RestoreSelf():Promise<void>;

export function RestoreSnapshot(arg1:string,arg2:boolean):Promise<void>;

export function ReverseScanSaves():Promise<match.ReverseScanResult>;

export function ScanBluetoothDevices():Promise<void>;

export function ScanLibrary():Promise<pipeline.Result>;

export function SearchManifest(arg1:string,arg2:number):Promise<Array<match.ManifestSearchResult>>;

export function SetAutoCheckUpdates(arg1:boolean):Promise<void>;

export function SetBackupRoot(arg1:string):Promise<void>;

export function SetDefaultAudioDevice(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetRetentionKeepN(arg1:number):Promise<void>;

export function SetSteamGridDBKey(arg1:string):Promise<void>;

export function SetSteamWebAPIKey(arg1:string):Promise<void>;

export function SetStoreAccountEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetVolumeMute(arg1:boolean):Promise<void>;

export function SetWatcherDebounceMinutes(arg1:number):Promise<void>;

export function ShowItemInFolder(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function SkipUpdate(arg1:string):Promise<void>;

export function SleepWorkstation():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SunshineClear():Promise<void>;

export function SunshineSync():Promise<void>;

export function SyncStoreAccount(arg1:string):Promise<void>;

export function SyncStoreLibraries():Promise<void>;

export function Toast(arg1:string,arg2:string):Promise<void>;

export function VolumeStepDown(arg1:number):Promise<void>;

export function VolumeStepUp(arg1:number):Promise<void>;

export function WatcherToggle(arg1:boolean):Promise<void>;
