// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {updater} from '../models';
import {context} from '../models';
import {match} from '../models';
import {main} from '../models';
import {config} from '../models';
import {display} from '../models';
import {backup} from '../models';
import {pipeline} from '../models';

export function AddManualSaveLocation(arg1:string,arg2:string):Promise<domain.SaveLocation>;

export function AppVersion():Promise<string>;

export function ApplyUpdate():Promise<void>;

export function BackupAll():Promise<number>;

export function BackupGame(arg1:string):Promise<Array<domain.Snapshot>>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function ClearManifestOverride(arg1:string):Promise<void>;

export function Context():Promise<context.Context>;

export function DeepScanGame(arg1:string):Promise<Array<match.DeepScanResult>>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function DisableShellMode():Promise<void>;

export function EnableShellMode():Promise<void>;

export function GetAutoLoginStatus():Promise<main.AutoLoginStatus>;

export function GetConfig():Promise<config.Config>;

export function GetGame(arg1:string):Promise<domain.GameView>;

export function GetShellModeStatus():Promise<main.ShellModeStatus>;

export function HideGame(arg1:string,arg2:boolean):Promise<void>;

export function IsControllerConnected():Promise<boolean>;

export function IsWatcherEnabled():Promise<boolean>;

export function LaunchGame(arg1:string,arg2:string):Promise<void>;

export function ListGames():Promise<Array<domain.GameView>>;

export function ListMonitors():Promise<Array<display.Monitor>>;

export function ListPlaySessions(arg1:string,arg2:number):Promise<Array<domain.PlaySession>>;

export function LockWorkstation():Promise<void>;

export function MakeSoleMonitor(arg1:string):Promise<void>;

export function OpenAutoLoginConfigurator():Promise<void>;

export function OpenBackupFolder():Promise<void>;

export function OpenWindowsSoundSettings():Promise<void>;

export function PickFolder(arg1:string):Promise<string>;

export function QuitApp():Promise<void>;

export function ReconcileBackups():Promise<backup.ReconcileResult>;

export function RematchGame(arg1:string,arg2:string):Promise<void>;

export function RemoveSaveLocation(arg1:string):Promise<void>;

export function RestartApp():Promise<void>;

export function RestoreMonitorConfig():Promise<void>;

export function RestoreSnapshot(arg1:string,arg2:boolean):Promise<void>;

export function ReverseScanSaves():Promise<match.ReverseScanResult>;

export function ScanLibrary():Promise<pipeline.Result>;

export function SearchManifest(arg1:string,arg2:number):Promise<Array<match.ManifestSearchResult>>;

export function SetAutoCheckUpdates(arg1:boolean):Promise<void>;

export function SetBackupRoot(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetRetentionKeepN(arg1:number):Promise<void>;

export function SetSteamGridDBKey(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetWatcherDebounceMinutes(arg1:number):Promise<void>;

export function ShowItemInFolder(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function SkipUpdate(arg1:string):Promise<void>;

export function SleepWorkstation():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Toast(arg1:string,arg2:string):Promise<void>;

export function WatcherToggle(arg1:boolean):Promise<void>;
