// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManualSaveLocation(arg1, arg2) {
  return window['go']['main']['App']['AddManualSaveLocation'](arg1, arg2);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function BackupAll() {
  return window['go']['main']['App']['BackupAll']();
}

export function BackupGame(arg1) {
  return window['go']['main']['App']['BackupGame'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearManifestOverride(arg1) {
  return window['go']['main']['App']['ClearManifestOverride'](arg1);
}

export function Context() {
  return window['go']['main']['App']['Context']();
}

export function DeepScanGame(arg1) {
  return window['go']['main']['App']['DeepScanGame'](arg1);
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function DisableShellMode() {
  return window['go']['main']['App']['DisableShellMode']();
}

export function EnableShellMode() {
  return window['go']['main']['App']['EnableShellMode']();
}

export function GetAutoLoginStatus() {
  return window['go']['main']['App']['GetAutoLoginStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGame(arg1) {
  return window['go']['main']['App']['GetGame'](arg1);
}

export function GetShellModeStatus() {
  return window['go']['main']['App']['GetShellModeStatus']();
}

export function HideGame(arg1, arg2) {
  return window['go']['main']['App']['HideGame'](arg1, arg2);
}

export function IsWatcherEnabled() {
  return window['go']['main']['App']['IsWatcherEnabled']();
}

export function LaunchGame(arg1, arg2) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2);
}

export function ListGames() {
  return window['go']['main']['App']['ListGames']();
}

export function ListMonitors() {
  return window['go']['main']['App']['ListMonitors']();
}

export function ListPlaySessions(arg1, arg2) {
  return window['go']['main']['App']['ListPlaySessions'](arg1, arg2);
}

export function MakeSoleMonitor(arg1) {
  return window['go']['main']['App']['MakeSoleMonitor'](arg1);
}

export function OpenAutoLoginConfigurator() {
  return window['go']['main']['App']['OpenAutoLoginConfigurator']();
}

export function OpenBackupFolder() {
  return window['go']['main']['App']['OpenBackupFolder']();
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReconcileBackups() {
  return window['go']['main']['App']['ReconcileBackups']();
}

export function RematchGame(arg1, arg2) {
  return window['go']['main']['App']['RematchGame'](arg1, arg2);
}

export function RemoveSaveLocation(arg1) {
  return window['go']['main']['App']['RemoveSaveLocation'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RestoreMonitorConfig() {
  return window['go']['main']['App']['RestoreMonitorConfig']();
}

export function RestoreSnapshot(arg1, arg2) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1, arg2);
}

export function ReverseScanSaves() {
  return window['go']['main']['App']['ReverseScanSaves']();
}

export function ScanLibrary() {
  return window['go']['main']['App']['ScanLibrary']();
}

export function SearchManifest(arg1, arg2) {
  return window['go']['main']['App']['SearchManifest'](arg1, arg2);
}

export function SetAutoCheckUpdates(arg1) {
  return window['go']['main']['App']['SetAutoCheckUpdates'](arg1);
}

export function SetBackupRoot(arg1) {
  return window['go']['main']['App']['SetBackupRoot'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetRetentionKeepN(arg1) {
  return window['go']['main']['App']['SetRetentionKeepN'](arg1);
}

export function SetSteamGridDBKey(arg1) {
  return window['go']['main']['App']['SetSteamGridDBKey'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetWatcherDebounceMinutes(arg1) {
  return window['go']['main']['App']['SetWatcherDebounceMinutes'](arg1);
}

export function ShowItemInFolder(arg1) {
  return window['go']['main']['App']['ShowItemInFolder'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function SkipUpdate(arg1) {
  return window['go']['main']['App']['SkipUpdate'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function Toast(arg1, arg2) {
  return window['go']['main']['App']['Toast'](arg1, arg2);
}

export function WatcherToggle(arg1) {
  return window['go']['main']['App']['WatcherToggle'](arg1);
}
